version: "3.6"

services:
  mongo-prod:
    restart: always
    container_name: ${MONGODB_CONTAINER_NAME}
    image: mongo:latest
    ports:
      - ${PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data:/data/db
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

volumes:
  mongodb:
  mongoconfig:

networks:
  default:
    external:
      name: prod
