version: "3.6"

services:
  cyberbrick:
    restart: always
    image: ${API_APP_V1_NAME}:${API_APP_V1_VERSION}
    container_name: ${API_CONTAINER_NAME}
    ports:
      - ${API_CONTAINER_PORT}:${API_CONTAINER_PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_CONF_EXT}:${VOLUME_CONF_INN}:ro
      - ${VOLUME_PUBLIC_EXT}:${VOLUME_PUBLIC_INN}:ro
      - ${VOLUME_FILE_EXT}:${VOLUME_FILE_INN}:ro
      - ${VOLUME_INN_DB_EXT}:${VOLUME_INN_DB_INN}:ro
    command: yarn start
    # tty: true

networks:
  default:
    external:
      name: prod
